function model_name = build_env_control_model()
%BUILD_ENV_CONTROL_MODEL Build a Simulink comparison model for PID and fuzzy-PID control.

addpath(fileparts(mfilename("fullpath")));
params = setup_env_control_params();
model_name = "env_control_compare";
model_path = fullfile(fileparts(mfilename("fullpath")), model_name + ".slx");

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

if exist(model_path, "file")
    delete(model_path);
end

load_system("simulink");
new_system(model_name);
set_param(model_name, "StopTime", num2str(params.stop_time));
set_param(model_name, "Solver", "ode4");
set_param(model_name, "FixedStep", num2str(params.sample_time));

add_controller_lane(model_name, "PID", 60, "env_control_pid_step(u)", params);
add_controller_lane(model_name, "FuzzyPID", 470, "env_control_fuzzy_pid_step(u)", params);

save_system(model_name, model_path);
open_system(model_name);
end

function add_controller_lane(model_name, lane_name, y0, controller_expr, params)
prefix = lane_name + "_";

x = struct( ...
    "const", 40, ...
    "mux", 260, ...
    "controller", 360, ...
    "demux", 520, ...
    "logic_mux", 650, ...
    "logic", 760, ...
    "logic_demux", 930, ...
    "plant_gain", 1040, ...
    "plant_sum", 1160, ...
    "integrator", 1280, ...
    "sink", 1440 ...
);

add_block("simulink/Sources/Constant", block(model_name, prefix + "TempSetpoint"), ...
    "Value", "params.setpoints.temperature_c", ...
    "Position", [x.const y0 + 10 x.const + 80 y0 + 40]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "HumidityThreshold"), ...
    "Value", "params.setpoints.humidity_pct", ...
    "Position", [x.const y0 + 60 x.const + 80 y0 + 90]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "SampleTime"), ...
    "Value", "params.sample_time", ...
    "Position", [x.const y0 + 110 x.const + 80 y0 + 140]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "CoolingOnAbove"), ...
    "Value", "params.logic.cooling_on_above", ...
    "Position", [x.const y0 + 160 x.const + 80 y0 + 190]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "CoolingOffAbove"), ...
    "Value", "params.logic.cooling_off_above", ...
    "Position", [x.const y0 + 210 x.const + 80 y0 + 240]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "HumidityHysteresis"), ...
    "Value", "params.logic.humidity_hysteresis", ...
    "Position", [x.const y0 + 260 x.const + 80 y0 + 290]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "AmbientTemp"), ...
    "Value", "params.plant.ambient_temp_c", ...
    "Position", [x.const + 760 y0 + 10 x.const + 840 y0 + 40]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "AmbientRH"), ...
    "Value", "params.plant.ambient_rh_pct", ...
    "Position", [x.const + 760 y0 + 210 x.const + 840 y0 + 240]);
add_block("simulink/Sources/Constant", block(model_name, prefix + "HumidifierDisturbance"), ...
    "Value", "params.disturbance.humidifier_on", ...
    "Position", [x.const + 760 y0 + 320 x.const + 840 y0 + 350]);
add_block("simulink/Sources/Step", block(model_name, prefix + "IceDisturbance"), ...
    "Time", "params.disturbance.ice_step_time_s", ...
    "Before", "0.0", ...
    "After", "params.disturbance.ice_step_amplitude", ...
    "Position", [x.const + 760 y0 + 370 x.const + 840 y0 + 400]);

add_block("simulink/Math Operations/Sum", block(model_name, prefix + "TempError"), ...
    "Inputs", "+-", ...
    "Position", [170 y0 + 15 200 y0 + 45]);

add_block("simulink/Discrete/Unit Delay", block(model_name, prefix + "IntegralState"), ...
    "InitialCondition", "0", ...
    "SampleTime", "params.sample_time", ...
    "Position", [210 y0 + 110 240 y0 + 140]);
add_block("simulink/Discrete/Unit Delay", block(model_name, prefix + "PrevErrorState"), ...
    "InitialCondition", "0", ...
    "SampleTime", "params.sample_time", ...
    "Position", [210 y0 + 160 240 y0 + 190]);
add_block("simulink/Discrete/Unit Delay", block(model_name, prefix + "HasPrevState"), ...
    "InitialCondition", "0", ...
    "SampleTime", "params.sample_time", ...
    "Position", [210 y0 + 210 240 y0 + 240]);

if lane_name == "PID"
    add_block("simulink/Sources/Constant", block(model_name, prefix + "Kp"), ...
        "Value", "params.pid.kp", ...
        "Position", [x.const y0 + 320 x.const + 80 y0 + 350]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "Ki"), ...
        "Value", "params.pid.ki", ...
        "Position", [x.const y0 + 360 x.const + 80 y0 + 390]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "Kd"), ...
        "Value", "params.pid.kd", ...
        "Position", [x.const y0 + 400 x.const + 80 y0 + 430]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "OutputLimit"), ...
        "Value", "params.pid.output_limit", ...
        "Position", [x.const y0 + 440 x.const + 80 y0 + 470]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "IntegralLimit"), ...
        "Value", "params.pid.integral_limit", ...
        "Position", [x.const y0 + 480 x.const + 80 y0 + 510]);

    add_block("simulink/Signal Routing/Mux", block(model_name, prefix + "ControllerMux"), ...
        "Inputs", "10", ...
        "Position", [x.mux y0 + 80 x.mux + 20 y0 + 300]);
else
    add_block("simulink/Sources/Constant", block(model_name, prefix + "BaseKp"), ...
        "Value", "params.fuzzy.base_kp", ...
        "Position", [x.const y0 + 320 x.const + 80 y0 + 350]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "BaseKi"), ...
        "Value", "params.fuzzy.base_ki", ...
        "Position", [x.const y0 + 360 x.const + 80 y0 + 390]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "BaseKd"), ...
        "Value", "params.fuzzy.base_kd", ...
        "Position", [x.const y0 + 400 x.const + 80 y0 + 430]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "OutputLimit"), ...
        "Value", "params.fuzzy.output_limit", ...
        "Position", [x.const y0 + 440 x.const + 80 y0 + 470]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "IntegralLimit"), ...
        "Value", "params.fuzzy.integral_limit", ...
        "Position", [x.const y0 + 480 x.const + 80 y0 + 510]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "ErrorScale"), ...
        "Value", "params.fuzzy.error_scale", ...
        "Position", [x.const y0 + 520 x.const + 80 y0 + 550]);
    add_block("simulink/Sources/Constant", block(model_name, prefix + "DeltaScale"), ...
        "Value", "params.fuzzy.delta_scale", ...
        "Position", [x.const y0 + 560 x.const + 80 y0 + 590]);

    add_block("simulink/Signal Routing/Mux", block(model_name, prefix + "ControllerMux"), ...
        "Inputs", "12", ...
        "Position", [x.mux y0 + 80 x.mux + 20 y0 + 340]);
end

add_block("simulink/User-Defined Functions/MATLAB Fcn", block(model_name, prefix + "Controller"), ...
    "MATLABFcn", controller_expr, ...
    "Position", [x.controller y0 + 120 x.controller + 120 y0 + 170]);
add_block("simulink/Signal Routing/Demux", block(model_name, prefix + "ControllerDemux"), ...
    "Outputs", "4", ...
    "Position", [x.demux y0 + 100 x.demux + 20 y0 + 220]);

add_block("simulink/Discrete/Unit Delay", block(model_name, prefix + "TempCoolingState"), ...
    "InitialCondition", "0", ...
    "SampleTime", "params.sample_time", ...
    "Position", [600 y0 + 220 630 y0 + 250]);
add_block("simulink/Discrete/Unit Delay", block(model_name, prefix + "VentilationState"), ...
    "InitialCondition", "0", ...
    "SampleTime", "params.sample_time", ...
    "Position", [600 y0 + 270 630 y0 + 300]);
add_block("simulink/Signal Routing/Mux", block(model_name, prefix + "ClimateMux"), ...
    "Inputs", "10", ...
    "Position", [x.logic_mux y0 + 40 x.logic_mux + 20 y0 + 300]);
add_block("simulink/User-Defined Functions/MATLAB Fcn", block(model_name, prefix + "ClimateLogic"), ...
    "MATLABFcn", "env_control_climate_logic(u)", ...
    "Position", [x.logic y0 + 120 x.logic + 140 y0 + 170]);
add_block("simulink/Signal Routing/Demux", block(model_name, prefix + "ClimateDemux"), ...
    "Outputs", "4", ...
    "Position", [x.logic_demux y0 + 90 x.logic_demux + 20 y0 + 220]);

add_block("simulink/Math Operations/Gain", block(model_name, prefix + "HeaterGain"), ...
    "Gain", "params.plant.k_heater", ...
    "Position", [x.plant_gain y0 + 20 x.plant_gain + 60 y0 + 50]);
add_block("simulink/Math Operations/Gain", block(model_name, prefix + "FanCoolingGain"), ...
    "Gain", "params.plant.k_fan_cooling", ...
    "Position", [x.plant_gain y0 + 70 x.plant_gain + 60 y0 + 100]);
add_block("simulink/Math Operations/Gain", block(model_name, prefix + "HumCoolingGain"), ...
    "Gain", "params.plant.k_humidifier_cooling", ...
    "Position", [x.plant_gain y0 + 120 x.plant_gain + 60 y0 + 150]);
add_block("simulink/Math Operations/Gain", block(model_name, prefix + "IceCoolingGain"), ...
    "Gain", "params.plant.k_ice_cooling", ...
    "Position", [x.plant_gain y0 + 170 x.plant_gain + 60 y0 + 200]);
add_block("simulink/Math Operations/Sum", block(model_name, prefix + "TempDynamicsSum"), ...
    "Inputs", "+-+---", ...
    "Position", [x.plant_sum y0 + 80 x.plant_sum + 40 y0 + 180]);
add_block("simulink/Math Operations/Gain", block(model_name, prefix + "TempTauInverse"), ...
    "Gain", "1 / params.plant.tau_temp_s", ...
    "Position", [x.plant_sum + 80 y0 + 110 x.plant_sum + 140 y0 + 140]);
add_block("simulink/Continuous/Integrator", block(model_name, prefix + "Temperature"), ...
    "InitialCondition", "params.plant.initial_temp_c", ...
    "Position", [x.integrator y0 + 105 x.integrator + 40 y0 + 145]);

add_block("simulink/Math Operations/Gain", block(model_name, prefix + "HumidifierRHGain"), ...
    "Gain", "params.plant.k_humidifier_rh", ...
    "Position", [x.plant_gain y0 + 250 x.plant_gain + 60 y0 + 280]);
add_block("simulink/Math Operations/Gain", block(model_name, prefix + "VentRHGain"), ...
    "Gain", "params.plant.k_vent_rh", ...
    "Position", [x.plant_gain y0 + 300 x.plant_gain + 60 y0 + 330]);
add_block("simulink/Math Operations/Sum", block(model_name, prefix + "RHDynamicsSum"), ...
    "Inputs", "+-+-", ...
    "Position", [x.plant_sum y0 + 250 x.plant_sum + 40 y0 + 330]);
add_block("simulink/Math Operations/Gain", block(model_name, prefix + "RHTauInverse"), ...
    "Gain", "1 / params.plant.tau_rh_s", ...
    "Position", [x.plant_sum + 80 y0 + 270 x.plant_sum + 140 y0 + 300]);
add_block("simulink/Continuous/Integrator", block(model_name, prefix + "RelativeHumidity"), ...
    "InitialCondition", "params.plant.initial_rh_pct", ...
    "Position", [x.integrator y0 + 265 x.integrator + 40 y0 + 305]);

add_block("simulink/Sinks/To Workspace", block(model_name, prefix + "TemperatureLog"), ...
    "VariableName", prefix + "temperature", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [x.sink y0 + 90 x.sink + 90 y0 + 120]);
add_block("simulink/Sinks/To Workspace", block(model_name, prefix + "HumidityLog"), ...
    "VariableName", prefix + "humidity", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [x.sink y0 + 250 x.sink + 90 y0 + 280]);
add_block("simulink/Sinks/To Workspace", block(model_name, prefix + "HeaterLog"), ...
    "VariableName", prefix + "heater", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [x.sink y0 + 140 x.sink + 90 y0 + 170]);
add_block("simulink/Sinks/To Workspace", block(model_name, prefix + "FanLog"), ...
    "VariableName", prefix + "fan", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [x.sink y0 + 190 x.sink + 90 y0 + 220]);
add_block("simulink/Sinks/Scope", block(model_name, prefix + "Scope"), ...
    "NumInputPorts", "4", ...
    "Position", [x.sink + 130 y0 + 120 x.sink + 180 y0 + 240]);

add_line(model_name, prefix + "TempSetpoint/1", prefix + "TempError/1", "autorouting", "on");
add_line(model_name, prefix + "Temperature/1", prefix + "TempError/2", "autorouting", "on");

add_line(model_name, prefix + "TempError/1", prefix + "ControllerMux/1", "autorouting", "on");
add_line(model_name, prefix + "SampleTime/1", prefix + "ControllerMux/2", "autorouting", "on");
add_line(model_name, prefix + "IntegralState/1", prefix + "ControllerMux/3", "autorouting", "on");
add_line(model_name, prefix + "PrevErrorState/1", prefix + "ControllerMux/4", "autorouting", "on");
add_line(model_name, prefix + "HasPrevState/1", prefix + "ControllerMux/5", "autorouting", "on");

if lane_name == "PID"
    add_line(model_name, prefix + "Kp/1", prefix + "ControllerMux/6", "autorouting", "on");
    add_line(model_name, prefix + "Ki/1", prefix + "ControllerMux/7", "autorouting", "on");
    add_line(model_name, prefix + "Kd/1", prefix + "ControllerMux/8", "autorouting", "on");
    add_line(model_name, prefix + "OutputLimit/1", prefix + "ControllerMux/9", "autorouting", "on");
    add_line(model_name, prefix + "IntegralLimit/1", prefix + "ControllerMux/10", "autorouting", "on");
else
    add_line(model_name, prefix + "BaseKp/1", prefix + "ControllerMux/6", "autorouting", "on");
    add_line(model_name, prefix + "BaseKi/1", prefix + "ControllerMux/7", "autorouting", "on");
    add_line(model_name, prefix + "BaseKd/1", prefix + "ControllerMux/8", "autorouting", "on");
    add_line(model_name, prefix + "OutputLimit/1", prefix + "ControllerMux/9", "autorouting", "on");
    add_line(model_name, prefix + "IntegralLimit/1", prefix + "ControllerMux/10", "autorouting", "on");
    add_line(model_name, prefix + "ErrorScale/1", prefix + "ControllerMux/11", "autorouting", "on");
    add_line(model_name, prefix + "DeltaScale/1", prefix + "ControllerMux/12", "autorouting", "on");
end

add_line(model_name, prefix + "ControllerMux/1", prefix + "Controller/1", "autorouting", "on");
add_line(model_name, prefix + "Controller/1", prefix + "ControllerDemux/1", "autorouting", "on");
add_line(model_name, prefix + "ControllerDemux/2", prefix + "IntegralState/1", "autorouting", "on");
add_line(model_name, prefix + "ControllerDemux/3", prefix + "PrevErrorState/1", "autorouting", "on");
add_line(model_name, prefix + "ControllerDemux/4", prefix + "HasPrevState/1", "autorouting", "on");

add_line(model_name, prefix + "ControllerDemux/1", prefix + "ClimateMux/1", "autorouting", "on");
add_line(model_name, prefix + "Temperature/1", prefix + "ClimateMux/2", "autorouting", "on");
add_line(model_name, prefix + "TempSetpoint/1", prefix + "ClimateMux/3", "autorouting", "on");
add_line(model_name, prefix + "RelativeHumidity/1", prefix + "ClimateMux/4", "autorouting", "on");
add_line(model_name, prefix + "HumidityThreshold/1", prefix + "ClimateMux/5", "autorouting", "on");
add_line(model_name, prefix + "CoolingOnAbove/1", prefix + "ClimateMux/6", "autorouting", "on");
add_line(model_name, prefix + "CoolingOffAbove/1", prefix + "ClimateMux/7", "autorouting", "on");
add_line(model_name, prefix + "HumidityHysteresis/1", prefix + "ClimateMux/8", "autorouting", "on");
add_line(model_name, prefix + "TempCoolingState/1", prefix + "ClimateMux/9", "autorouting", "on");
add_line(model_name, prefix + "VentilationState/1", prefix + "ClimateMux/10", "autorouting", "on");
add_line(model_name, prefix + "ClimateMux/1", prefix + "ClimateLogic/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateLogic/1", prefix + "ClimateDemux/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/3", prefix + "VentilationState/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/4", prefix + "TempCoolingState/1", "autorouting", "on");

add_line(model_name, prefix + "ClimateDemux/1", prefix + "HeaterGain/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/2", prefix + "FanCoolingGain/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/2", prefix + "VentRHGain/1", "autorouting", "on");
add_line(model_name, prefix + "HumidifierDisturbance/1", prefix + "HumCoolingGain/1", "autorouting", "on");
add_line(model_name, prefix + "HumidifierDisturbance/1", prefix + "HumidifierRHGain/1", "autorouting", "on");
add_line(model_name, prefix + "IceDisturbance/1", prefix + "IceCoolingGain/1", "autorouting", "on");

add_line(model_name, prefix + "AmbientTemp/1", prefix + "TempDynamicsSum/1", "autorouting", "on");
add_line(model_name, prefix + "Temperature/1", prefix + "TempDynamicsSum/2", "autorouting", "on");
add_line(model_name, prefix + "HeaterGain/1", prefix + "TempDynamicsSum/3", "autorouting", "on");
add_line(model_name, prefix + "FanCoolingGain/1", prefix + "TempDynamicsSum/4", "autorouting", "on");
add_line(model_name, prefix + "HumCoolingGain/1", prefix + "TempDynamicsSum/5", "autorouting", "on");
add_line(model_name, prefix + "IceCoolingGain/1", prefix + "TempDynamicsSum/6", "autorouting", "on");
add_line(model_name, prefix + "TempDynamicsSum/1", prefix + "TempTauInverse/1", "autorouting", "on");
add_line(model_name, prefix + "TempTauInverse/1", prefix + "Temperature/1", "autorouting", "on");

add_line(model_name, prefix + "AmbientRH/1", prefix + "RHDynamicsSum/1", "autorouting", "on");
add_line(model_name, prefix + "RelativeHumidity/1", prefix + "RHDynamicsSum/2", "autorouting", "on");
add_line(model_name, prefix + "HumidifierRHGain/1", prefix + "RHDynamicsSum/3", "autorouting", "on");
add_line(model_name, prefix + "VentRHGain/1", prefix + "RHDynamicsSum/4", "autorouting", "on");
add_line(model_name, prefix + "RHDynamicsSum/1", prefix + "RHTauInverse/1", "autorouting", "on");
add_line(model_name, prefix + "RHTauInverse/1", prefix + "RelativeHumidity/1", "autorouting", "on");

add_line(model_name, prefix + "Temperature/1", prefix + "TemperatureLog/1", "autorouting", "on");
add_line(model_name, prefix + "RelativeHumidity/1", prefix + "HumidityLog/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/1", prefix + "HeaterLog/1", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/2", prefix + "FanLog/1", "autorouting", "on");
add_line(model_name, prefix + "Temperature/1", prefix + "Scope/1", "autorouting", "on");
add_line(model_name, prefix + "RelativeHumidity/1", prefix + "Scope/2", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/1", prefix + "Scope/3", "autorouting", "on");
add_line(model_name, prefix + "ClimateDemux/2", prefix + "Scope/4", "autorouting", "on");
end

function path_value = block(model_name, block_name)
path_value = char(model_name + "/" + block_name);
end
